name: DevOps Demo Day Pipeline

on:
  push:
    branches: [ "main" ]

env:
  DOCKER_USER: kranio
  DOCKER_IMAGE_NAME: kranio/app-demoday:latest
  APP_NAME: app-demoday
  SERVICE_NAME: service-demoday

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar Koyeb CLI Manualmente
        run: |
          curl https://raw.githubusercontent.com/koyeb/koyeb-cli/master/install.sh | sh
          echo "$HOME/.koyeb/bin" >> $GITHUB_PATH

      - name: Verificar e Implantar no Koyeb
        env:
          KOYEB_TOKEN: ${{ secrets.KOYEB_TOKEN }}
        run: |
          export KOYEB_TOKEN=${{ secrets.KOYEB_TOKEN }}
          
          if ! koyeb app get ${{ env.APP_NAME }} > /dev/null 2>&1; then
            koyeb app create ${{ env.APP_NAME }}
          fi

          if koyeb service get ${{ env.APP_NAME }}/${{ env.SERVICE_NAME }} > /dev/null 2>&1; then
            echo "Atualizando serviço existente..."
            koyeb service redeploy ${{ env.APP_NAME }}/${{ env.SERVICE_NAME }}
          else
            echo "Criando novo serviço..."
            koyeb service create ${{ env.APP_NAME }}/${{ env.SERVICE_NAME }} \
              --docker ${{ env.DOCKER_IMAGE_NAME }} \
              --instance-type nano \
              --port 5000:http \
              --route /:5000
          fi